
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import { GameProvider } from "../contexts/GameContext"; // Import GameProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CoupleQuestions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="my-theme" className="bg-base-300">
      {/* <head className="bg-base-300"></head> */}
      <body className="bg-base-300">
        <GameProvider>
          <AuthProvider>
          {children}
          </AuthProvider>
        </GameProvider>
      </body>
    </html>
  );
}
